config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'todo_lists#index', as: 'todo_lists'
  get 'todo_lists/new', to: 'todo_lists#new', as: 'new_todo_list'
  post 'todo_lists', to: 'todo_lists#create', as: 'create_todo_list'
  get '/todo_lists/:id', to: 'todo_lists#show', as: 'todo_list'
  get '/todo_lists/:id/edit', to: 'todo_lists#edit', as: 'edit_todo_list'
  patch '/todo_lists/:id', to: 'todo_lists#update', as: 'update_todo_list'
  delete 'todo_lists/:id', to: 'todo_lists#destroy', as: 'delete_todo_list'

  post '/todo_list_items', to: 'todo_list_items#create'
  get  '/todo_list_items/new', to: 'todo_list_items#new', as: 'new_todo_list_item'
  get    '/todo_list_items/:id/edit', to: 'todo_list_items#edit', as: 'edit_todo_list_item'
  get    '/todo_list_items/:id', to: 'todo_list_items#show', as: 'todo_list_item'
  patch  '/todo_list_items/:id', to: 'todo_list_items#update'
  put    '/todo_list_items/:id', to: 'todo_list_items#update'
  delete '/todo_list_items/:id', to: 'todo_list_items#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_list_items
  # accepts_nested_attributes_for :todo_list_items
  validates :title, presence: true

  def improve_title_text
    # if self.valid?
      title.titleize
    # end
  end
end

app/models/todo_list_item.rb
class TodoListItem < ApplicationRecord
  belongs_to :todo_list
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_list_items_controller.rb
class TodoListItemsController < ApplicationController
  def new
    @todo_list = TodoList.find(params[:id])
    @todo_list_items = @todo_list.todo_list_items.new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  def index
    @todo_lists = TodoList.all
    respond_to do |format|
        format.html
        format.json do
          render json: @todo_lists
        end
      end
  end

  def show
    @todo_list = TodoList.find(params[:id])
    respond_to do |format|
      format.html
      format.json do
        render json: @todo_list
      end
    end
  end

  def new
    @todo_list = TodoList.new
    respond_to do |format|
      format.html
      format.json do
        render json: @todo_list
      end
    end
  end

  def create
  end

  def edit
    @todo_list = TodoList.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_list_items_helper.rb
module TodoListItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
  def display_form_errors(errors)
    if errors.class == Array
      if errors.count > 1
        errors[0..-2].join() + ", " + errors[-1]
      else
        errors.pop if errors.count == 1
      end
    else
      errors
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo List App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Including Materialize into the project -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_list_items/edit.html.erb
<h2>Item: <%= @todo_list_item.description %></h2>

<p style="color:red;"><%= display_form_errors(flash[:error]) if flash[:error] %></p>
<p style="color:green;"><%= flash[:success] if flash[:success] %></p>

<%= form_for @todo_list_item do |f| %>
	<p>Description: <%= f.text_field :description %></p>	
	<p>Done: <%= f.check_box :completed %></p>	
	<%= f.submit "Update" %>
<% end %>

<br>
<%= link_to "Todo List", todo_list_path(@todo_list_item.todo_list) %> |
<%= link_to "Home Page", todo_lists_path %>

app/views/todo_lists/edit.html.erb
<h1><%= @todo_list.improve_title_text %></h1>

<% if flash[:error] %>
	<!-- <p style="color:red"><%#= display_form_errors(flash[:error]) %></p> -->
	<p style="color:red"><%= flash[:error] %></p>
<% end %>

<%= form_for @todo_list, url: { action: "update" } do |f| %>
	<%= f.text_field :title %>
<%= f.submit %>
<% end %>

<h2>Items:</h2>
<% @todo_list.todo_list_items.each do |item|  %>
	<%#= form_tag todo_list_item_path(item), method: :patch do %>
		<%#= text_field_tag :description, item.description, name: "todo_list_item[description]" %>
		<%#= submit_tag "Update" %>
	<%# end %>
	<%= form_for item do |f| %>
		<%= f.text_field :description %>
		<%= f.label :done %>
		<%= f.check_box :completed %>
		<%= f.submit %>
	<% end %>
<% end %>
<br>
<%= link_to "Homepage", todo_lists_path %>

app/views/todo_lists/index.html.erb
<div class="container">
	<h1 style="text-align:center;">My Todo Lists</h1>

	<% if flash[:notice] %>
		<%= flash[:notice] %>
	<% end %>

	<% if @todo_lists.empty? %>
		<%= link_to "Create your first Todo List", new_todo_list_path %>
	<% else %>
		<% @todo_lists.each do |todo_list| %>
			<div class="row" style="border-bottom: 2px solid whitesmoke;">
				<b>Title:</b> <%= todo_list.title %> 
				<p>
					<%= link_to "view", todo_list_path(todo_list.id) %> |
					<%= link_to "edit", edit_todo_list_path(todo_list.id) %> |
					<%= link_to "delete", delete_todo_list_path(todo_list.id), method: :delete, data: { confirm: "Are you sure?" } %>
				</p>
			</div>
		<% end %>
	<% end %>
	<button class="waves-effect waves-light btn"><%= link_to "New TodoList", new_todo_list_path %> </button>
</div>


<style>
	button a{
		color:white;
	}
</style>

app/views/todo_lists/new.html.erb
<h2>Create a Todo List</h2>

<p style="color:red;"><%= display_form_errors(flash[:error]) if flash[:error] %></p>
<p style="color:green;"><%= flash[:success] if flash[:success] %></p>

<%= form_for @todo_list, url: { action: :create } do |f| %>
	<%= f.text_field :title, placeholder: "Enter a Title" %>
	<%= f.submit %>
<% end %>

<br>

<button><%= link_to "Home Page", todo_lists_path %></button>

app/views/todo_lists/show.html.erb
<h2><%= @todo_list.improve_title_text %></h2> 

<p style="color:red;"><%= display_form_errors(flash[:error]) if flash[:error] %></p>
<p style="color:green;"><%= flash[:success] if flash[:success] %></p>

<%= form_for @todo_list.todo_list_items.build do |f| %> 
	<%= f.text_field :description, place_holder: "write your description here" %>
	<%= f.hidden_field :todo_list_id, value: @todo_list.id %>
	<%= f.submit "Create a todo list item" %>
<% end %>

<h3>Todo List Items:</h3>
<% @todo_list.todo_list_items.reload.each do |item| %>
	<p>
		<% if item.completed? %>
			<span id='desc'>item.description</span> 
		<% else %>
			<%= item.description %>
		<% end %>
		<%= link_to "Edit", edit_todo_list_item_path(item) %> |
		<%= link_to "Delete", todo_list_item_path(item), method: :delete, data: { confirm: "Are you sure?" } %>
	</p>
<% end %>

<%= link_to "Homepage", todo_lists_path %>

<style>
	#desc {
		text-decoration: line-through;
	}
</style>